STORE_CURRENCY = "RUB"

BUSINESS_PROFILE = {
    "brand_name": "Кунжут",
    "address": "ул. Дзержинского, 18",
    "map_url": "https://yandex.ru/navi/org/kunzhut/164627838144?si=h642xhuqxfhvq70ru31nkj80c4",
    "instagram_url": "https://www.instagram.com/kunzhut.food?igsh=dXVtODRxOXhrZmow",
    "vk_url": "https://vk.ru/kunzhutfood",
}

CATEGORIES = [
    {"id": "popular", "title": "Хиты вечера"},
    {"id": "pizza", "title": "Пицца"},
    {"id": "combos", "title": "Комбо"},
    {"id": "snacks", "title": "Закуски"},
    {"id": "desserts", "title": "Десерты"},
    {"id": "drinks", "title": "Напитки"},
]

MENU_ITEMS = [
    {
        "id": "kungfu-sesame",
        "category_id": "popular",
        "title": "Кунг-фу кунжут",
        "tag": "Фирменная",
        "description": "Цыпленок терияки, кунжутный соус, перец рамиро, моцарелла и зеленый лук.",
        "price": 589,
        "weight": "680 г",
        "badge": "Хит",
        "accent": "#ff7f32",
    },
    {
        "id": "volcano-shrimp",
        "category_id": "popular",
        "title": "Вулкан с креветкой",
        "tag": "Острая",
        "description": "Креветки, чили-мед, томаты конкассе, сырный соус и хрустящий кунжут.",
        "price": 649,
        "weight": "710 г",
        "badge": "Новинка",
        "accent": "#f04e30",
    },
    {
        "id": "garden-margherita",
        "category_id": "pizza",
        "title": "Садовая маргарита",
        "tag": "Легкая",
        "description": "Томатный соус, базилик, моцарелла, сладкие томаты и оливковое масло.",
        "price": 429,
        "weight": "540 г",
        "accent": "#f6b347",
    },
    {
        "id": "smoked-beef-bbq",
        "category_id": "pizza",
        "title": "Копченая говядина BBQ",
        "tag": "На компанию",
        "description": "Говядина slow-cook, барбекю, красный лук, моцарелла и пряные огурцы.",
        "price": 699,
        "weight": "760 г",
        "accent": "#d95b43",
    },
    {
        "id": "cheese-drift",
        "category_id": "pizza",
        "title": "Сырный дрифт",
        "tag": "Сливочная",
        "description": "Моцарелла, чеддер, пармезан, сырный соус и карамелизированный лук.",
        "price": 559,
        "weight": "650 г",
        "accent": "#ffcf5a",
    },
    {
        "id": "duo-date",
        "category_id": "combos",
        "title": "Комбо на двоих",
        "tag": "Выгодно",
        "description": "2 пиццы 25 см, картофельные дольки и 2 лимонада.",
        "price": 1190,
        "weight": "1 сет",
        "badge": "-12%",
        "accent": "#ff9f1c",
    },
    {
        "id": "office-party",
        "category_id": "combos",
        "title": "Офисный рейс",
        "tag": "Для команды",
        "description": "3 большие пиццы, крылья, соусы и 4 напитка.",
        "price": 2490,
        "weight": "1 сет",
        "badge": "-18%",
        "accent": "#ff6f61",
    },
    {
        "id": "truffle-potatoes",
        "category_id": "snacks",
        "title": "Трюфельные дольки",
        "tag": "Горячее",
        "description": "Печеный картофель, трюфельное масло, пармезан и травы.",
        "price": 259,
        "weight": "180 г",
        "accent": "#b56576",
    },
    {
        "id": "sesame-wings",
        "category_id": "snacks",
        "title": "Крылья sweet chili",
        "tag": "Острые",
        "description": "Куриные крылья в глазури sweet chili с кунжутом и кинзой.",
        "price": 349,
        "weight": "240 г",
        "accent": "#ef476f",
    },
    {
        "id": "basque-caramel",
        "category_id": "desserts",
        "title": "Баскский чизкейк",
        "tag": "Десерт",
        "description": "Нежный чизкейк с карамельной корочкой и соленой карамелью.",
        "price": 279,
        "weight": "140 г",
        "accent": "#c97b63",
    },
    {
        "id": "orange-tonic",
        "category_id": "drinks",
        "title": "Апельсин-тоник",
        "tag": "Освежает",
        "description": "Домашний цитрусовый лимонад с тоником и розмарином.",
        "price": 189,
        "weight": "400 мл",
        "accent": "#3fa34d",
    },
]

FEATURES = [
    {"title": "30 минут до двери", "text": "Собираем и отправляем самые популярные позиции без ожидания."},
    {"title": "Адрес", "text": "Кунжут ждёт гостей на ул. Дзержинского, 18."},
    {"title": "Кунжутик рекомендует", "text": "У каждого хита есть короткая видео-история и фирменный совет по подаче."},
]

PROMOS = [
    {"title": "Пицца недели", "text": "Кунг-фу кунжут со скидкой 15% до полуночи воскресенья."},
    {"title": "Первый заказ", "text": "Десерт в подарок при заказе от 1 500 ₽."},
]
