STORE_CURRENCY = "RUB"

BUSINESS_PROFILE = {
    "brand_name": "Кунжут",
    "address": "ул. Дзержинского, 18",
    "city": "Солнечногорск",
    "phone": "+7 (916) 498-39-09",
    "hours": "ежедневно с 10:00 до 22:00",
    "map_url": "https://yandex.ru/navi/org/kunzhut/164627838144?si=h642xhuqxfhvq70ru31nkj80c4",
    "instagram_url": "https://www.instagram.com/kunzhut.food?igsh=dXVtODRxOXhrZmow",
    "vk_url": "https://vk.ru/kunzhutfood",
    "menu_source_url": "https://o-eda-dostavka.ru/goroda/solnechnogorsk/rest/kunzhut_w5d9c/",
    "menu_source_note": "Цены и позиции сверены по открытой карточке меню, актуальность источника может отличаться от фактической.",
}

CATEGORIES = [
    {"id": "doners", "title": "Донеры"},
    {"id": "combos", "title": "Комбо"},
    {"id": "sides", "title": "Гарниры"},
    {"id": "coffee", "title": "Чай и кофе"},
    {"id": "desserts", "title": "Десерты"},
    {"id": "cold_drinks", "title": "Холодные напитки"},
    {"id": "middle_east", "title": "Ближний Восток"},
    {"id": "seasonal", "title": "Сезонное меню"},
    {"id": "bubble", "title": "Бабл"},
    {"id": "soups", "title": "Супы"},
    {"id": "salads", "title": "Салаты"},
]

MENU_ITEMS = [
    {
        "id": "doner-bread",
        "category_id": "doners",
        "title": "Донер в хлебе",
        "tag": "Турецкий донер",
        "description": "Сытный донер в тёплом хлебе: мясо, свежие овощи и соус.",
        "price": 350,
        "weight": "300 г",
        "badge": "Хит",
        "accent": "#ff7f32",
    },
    {
        "id": "doner-plate",
        "category_id": "doners",
        "title": "Донер на тарелке",
        "tag": "Сытный обед",
        "description": "Куриное филе, помидор, красный лук, томатный соус, картофель и лаваш.",
        "price": 400,
        "weight": "300 г",
        "accent": "#f04e30",
    },
    {
        "id": "doner-lavash",
        "category_id": "doners",
        "title": "Донер в лаваше",
        "tag": "С собой",
        "description": "Мясо, овощи и соус в лаваше. Удобный формат для быстрого перекуса.",
        "price": 330,
        "weight": "300 г",
        "accent": "#f6b347",
    },
    {
        "id": "chicken-pilav",
        "category_id": "doners",
        "title": "Пилав с курицей",
        "tag": "Горячее",
        "description": "Курица на гриле, рис, фета, кукуруза, красный лук, помидор и капуста.",
        "price": 400,
        "weight": "300 г",
        "accent": "#d95b43",
    },
    {
        "id": "combo-kunzhut",
        "category_id": "combos",
        "title": "Комбо Кунжут",
        "tag": "Комбо",
        "description": "Донер и картофель фри.",
        "price": 400,
        "weight": "440 г",
        "badge": "Популярно",
        "accent": "#ff9f1c",
    },
    {
        "id": "combo-all-inclusive",
        "category_id": "combos",
        "title": "Комбо Всё включено",
        "tag": "Большой обед",
        "description": "Турецкий донер, картофель фри и Добрый Лимон-лайм.",
        "price": 470,
        "weight": "440 г",
        "accent": "#ff6f61",
    },
    {
        "id": "fries",
        "category_id": "sides",
        "title": "Картофель фри",
        "tag": "Гарнир",
        "description": "Классический картофель фри к донеру или комбо.",
        "price": 180,
        "weight": "140 г",
        "accent": "#b56576",
    },
    {
        "id": "latte",
        "category_id": "coffee",
        "title": "Латте",
        "tag": "Кофе",
        "description": "Мягкий молочный кофе.",
        "price": 300,
        "weight": "400 мл",
        "accent": "#c97b63",
    },
    {"id": "black-tea", "category_id": "coffee", "title": "Чай черный", "tag": "Чай", "description": "Горячий черный чай.", "price": 150, "weight": "300 мл", "accent": "#9a6b4f"},
    {"id": "green-tea", "category_id": "coffee", "title": "Чай зеленый", "tag": "Чай", "description": "Горячий зеленый чай.", "price": 150, "weight": "300 мл", "accent": "#6c9a4f"},
    {"id": "cappuccino", "category_id": "coffee", "title": "Капучино", "tag": "Кофе", "description": "Классический капучино.", "price": 250, "weight": "300 мл", "accent": "#b4835d"},
    {"id": "americano", "category_id": "coffee", "title": "Американо", "tag": "Кофе", "description": "Чёрный кофе без молока.", "price": 180, "weight": "200 мл", "accent": "#7b4a2f"},
    {"id": "raf", "category_id": "coffee", "title": "Раф", "tag": "Кофе", "description": "Сливочный кофейный напиток.", "price": 350, "weight": "400 мл", "accent": "#d3a06a"},
    {"id": "cocoa-marshmallow", "category_id": "coffee", "title": "Какао с маршмеллоу", "tag": "Какао", "description": "Горячее какао с маршмеллоу.", "price": 250, "weight": "300 мл", "accent": "#a66a4a"},
    {"id": "salep", "category_id": "coffee", "title": "Турецкий салеп", "tag": "Турецкий напиток", "description": "Тёплый турецкий напиток.", "price": 190, "weight": "300 мл", "accent": "#d8b76f"},
    {"id": "turkish-coffee", "category_id": "coffee", "title": "Кофе по-турецки", "tag": "Кофе", "description": "Плотный кофе в турецком стиле.", "price": 200, "weight": "200 мл", "accent": "#83543a"},
    {"id": "chocolate-sausage", "category_id": "desserts", "title": "Шоколадная колбаса", "tag": "Десерт", "description": "Небольшой шоколадный десерт.", "price": 70, "weight": "50 г", "accent": "#7c4a3b"},
    {"id": "kunzhut-candy", "category_id": "desserts", "title": "Конфета Кунжут", "tag": "Десерт", "description": "Фирменная конфета к кофе или чаю.", "price": 60, "weight": "35 г", "accent": "#d6a75c"},
    {"id": "shu-pistachio-raspberry", "category_id": "desserts", "title": "Шу Фисташка с малиной", "tag": "Десерт", "description": "Заварной десерт с фисташкой и малиной.", "price": 170, "weight": "55 г", "accent": "#8ab36f"},
    {"id": "shu-berry", "category_id": "desserts", "title": "Шу Ягодное", "tag": "Десерт", "description": "Лёгкий ягодный десерт.", "price": 170, "weight": "55 г", "accent": "#c45b7a"},
    {"id": "shu-nut", "category_id": "desserts", "title": "Шу Орех", "tag": "Десерт", "description": "Заварной десерт с ореховым акцентом.", "price": 170, "weight": "55 г", "accent": "#b67a45"},
    {"id": "waffle-condensed-milk", "category_id": "desserts", "title": "Трубочка вафельная со сгущенкой", "tag": "Десерт", "description": "Вафельная трубочка с варёной сгущёнкой.", "price": 150, "weight": "75 г", "accent": "#d59b5b"},
    {"id": "nutella-banana-pancakes", "category_id": "desserts", "title": "Блины с нутеллой и бананом", "tag": "Десерт", "description": "Два блина с нутеллой и бананом.", "price": 220, "weight": "120 г", "accent": "#c88b5c"},
    {"id": "dobry-cola", "category_id": "cold_drinks", "title": "Добрый Cola", "tag": "Напиток", "description": "Газированный напиток.", "price": 120, "weight": "330 мл", "accent": "#5b3a2e"},
    {"id": "dobry-lime", "category_id": "cold_drinks", "title": "Добрый Лимон-лайм", "tag": "Напиток", "description": "Освежающий лимон-лайм.", "price": 120, "weight": "330 мл", "accent": "#94b95f"},
    {"id": "dobry-orange", "category_id": "cold_drinks", "title": "Добрый Апельсин", "tag": "Напиток", "description": "Апельсиновый газированный напиток.", "price": 120, "weight": "330 мл", "accent": "#f58b3c"},
    {"id": "ayran", "category_id": "cold_drinks", "title": "Айран 2%", "tag": "Напиток", "description": "Традиционный холодный кисломолочный напиток.", "price": 100, "weight": "400 г", "accent": "#76a6b8"},
    {"id": "pomegranate-juice", "category_id": "cold_drinks", "title": "Сок гранатовый", "tag": "Напиток", "description": "Гранатовый сок.", "price": 100, "weight": "300 мл", "accent": "#b0263a"},
    {"id": "baklava-baku", "category_id": "middle_east", "title": "Пахлава Бакинская", "tag": "Восточная сладость", "description": "Классическая пахлава.", "price": 150, "weight": "100 г", "accent": "#c98734"},
    {"id": "baklava-walnut", "category_id": "middle_east", "title": "Пахлава с грецким орехом", "tag": "Восточная сладость", "description": "Пахлава с грецким орехом.", "price": 150, "weight": "100 г", "accent": "#a86b32"},
    {"id": "baklava-pistachio", "category_id": "middle_east", "title": "Пахлава с фисташкой", "tag": "Восточная сладость", "description": "Пахлава с фисташкой.", "price": 150, "weight": "100 г", "accent": "#93a847"},
    {"id": "rahat-assorted", "category_id": "middle_east", "title": "Рахат ассорти", "tag": "Восточная сладость", "description": "Ассорти рахат-лукума с орехами и фруктовыми нотами.", "price": 700, "weight": "310 г", "accent": "#d9a441"},
    {"id": "espresso-tonic", "category_id": "seasonal", "title": "Эспрессо-тоник", "tag": "Сезонное", "description": "Холодный кофе с тоником.", "price": 290, "weight": "500 мл", "accent": "#c5cf6a"},
    {"id": "ice-latte", "category_id": "seasonal", "title": "Айс-латте", "tag": "Сезонное", "description": "Холодный латте.", "price": 220, "weight": "500 мл", "accent": "#cfaa73"},
    {"id": "bumble-coffee", "category_id": "seasonal", "title": "Бамбл кофе", "tag": "Сезонное", "description": "Освежающий кофейный напиток.", "price": 300, "weight": "500 мл", "accent": "#e38d32"},
    {"id": "pomegranate-bumble", "category_id": "seasonal", "title": "Гранатовый бамбл", "tag": "Сезонное", "description": "Холодный напиток с гранатовым акцентом.", "price": 300, "weight": "500 мл", "accent": "#b92642"},
    {"id": "ice-cocoa", "category_id": "seasonal", "title": "Айс какао", "tag": "Сезонное", "description": "Холодное какао.", "price": 250, "weight": "500 мл", "accent": "#8d5c45"},
    {"id": "bubble-coffee", "category_id": "bubble", "title": "Бабл кофе", "tag": "Бабл", "description": "Эспрессо, молоко, сироп солёная карамель и тапиока.", "price": 410, "weight": "600 мл", "accent": "#b77a55"},
    {"id": "bubble-matcha", "category_id": "bubble", "title": "Бабл матча", "tag": "Бабл", "description": "Молоко, матча и тапиока.", "price": 410, "weight": "600 мл", "accent": "#83a85a"},
    {"id": "lentil-soup", "category_id": "soups", "title": "Суп-пюре чечевичный", "tag": "Суп", "description": "Красная чечевица, лук, болгарский перец и морковь.", "price": 150, "weight": "300 г", "accent": "#d88236"},
    {"id": "caesar-salad", "category_id": "salads", "title": "Салат Цезарь", "tag": "Салат", "description": "Айсберг, помидор черри, куриное филе, сыр и соус.", "price": 320, "weight": "220 г", "accent": "#72a75c"},
    {"id": "grilled-vegetable-salad", "category_id": "salads", "title": "Салат овощной на мангале", "tag": "Салат", "description": "Овощи на мангале с зеленью и ароматом костра.", "price": 200, "weight": "200 г", "accent": "#d56d42"},
]

FEATURES = [
    {"title": "Донеры и турецкая кухня", "text": "В меню донеры, пилав, чечевичный суп, пахлава и горячие напитки."},
    {"title": "Адрес", "text": "Кунжут ждёт гостей на ул. Дзержинского, 18."},
    {"title": "Заказ и самовывоз", "text": "Оформляйте заказ на сайте или приходите за горячим донером на месте."},
]

PROMOS = [
    {"title": "Комбо Кунжут", "text": "Донер и картофель фри в одном сытном наборе."},
    {"title": "Восточные сладости", "text": "Пахлава, рахат ассорти и фирменные десерты к кофе."},
]
